### ISSUE TITLE
Starting Neo4j Server failed

### ISSUE THREAD

**Issue by nurolopher** [Graphify/graphify#23]
Getting the following error when adding plugin to **neo4j-community 2.2.1 32bit**.
Cloned from the **master** branch.
Java version **7u45 32bit**
Windows 64bit.

```
Starting Neo4j Server failed: javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-259749@3b1f74ba==org.neo4j.server.web.NeoServletContainer,-1,false
```

**Comment by kbastani** [comment]
Can you try upgrading to JDK 8?

**Comment by nurolopher** [comment]
I tried but didn't work for the community edition. Then installed Enterprise edition with Java 8 and worked.

**Comment by kbastani** [comment]
Ok I will investigate more but I am glad you were able to get it working.

**Comment by pedrodavidept** [comment]
I have the same problem of @nurolopher . I'm using Neo4J 2.3.8 Community Edition and I got: 

Starting Neo4j failed: org.neo4j.server.web.NeoServletContainer-8e636ad@b7f1189b==org.neo4j.server.web.NeoServletContainer,-1,false

![captura de ecra 2016-12-05 as 23 34 41](https://cloud.githubusercontent.com/assets/16099067/20907025/7375adc8-bb43-11e6-8440-0089bed446c6.png)

I'me using JDK8.
