### ISSUE TITLE
Multiple graphs

### ISSUE THREAD

**Issue by cicero19** [Graphify/graphify#26]
Hi Kenny,

I'm wondering if there is a way to use a single instance of neo4j + graphify to train multiple graphs. For example, movie reviews and book reviews in a single database but unrelated. During classification you would need to specify which graph you want to use to classify. The current labels look like "class", "pattern" and "data". Presumably these would need to be duplicated for this case. Does this make sense? Any way to do it currently?

Thanks!

**Comment by kbastani** [comment]
Hi Mark,

Take a look at this spec: https://github.com/Graphify/graphify/issues/19

It's partially implemented in the 1.0.0-M01 branch. Hoping to have some time soon to merge it in.
